/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsCaptureRouteImport } from './routes/ops/capture'
import { Route as OpsConsultsRouteImport } from './routes/ops/consults'
import { Route as OpsExceptionsRouteImport } from './routes/ops/exceptions'
import { Route as OpsPacketsRouteImport } from './routes/ops/packets'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OpsJourneysIdRouteImport } from './routes/ops/journeys.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCaptureRoute = OpsCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => OpsRoute,
} as any)
const OpsConsultsRoute = OpsConsultsRouteImport.update({
  id: '/consults',
  path: '/consults',
  getParentRoute: () => OpsRoute,
} as any)
const OpsExceptionsRoute = OpsExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPacketsRoute = OpsPacketsRouteImport.update({
  id: '/packets',
  path: '/packets',
  getParentRoute: () => OpsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsJourneysIdRoute = OpsJourneysIdRouteImport.update({
  id: '/journeys/$id',
  path: '/journeys/$id',
  getParentRoute: () => OpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/ops/capture': typeof OpsCaptureRoute
  '/ops/consults': typeof OpsConsultsRoute
  '/ops/exceptions': typeof OpsExceptionsRoute
  '/ops/packets': typeof OpsPacketsRoute
  '/ops/': typeof OpsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ops/journeys/$id': typeof OpsJourneysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops/capture': typeof OpsCaptureRoute
  '/ops/consults': typeof OpsConsultsRoute
  '/ops/exceptions': typeof OpsExceptionsRoute
  '/ops/packets': typeof OpsPacketsRoute
  '/ops': typeof OpsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ops/journeys/$id': typeof OpsJourneysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/ops/capture': typeof OpsCaptureRoute
  '/ops/consults': typeof OpsConsultsRoute
  '/ops/exceptions': typeof OpsExceptionsRoute
  '/ops/packets': typeof OpsPacketsRoute
  '/ops/': typeof OpsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ops/journeys/$id': typeof OpsJourneysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ops'
    | '/ops/capture'
    | '/ops/consults'
    | '/ops/exceptions'
    | '/ops/packets'
    | '/ops/'
    | '/api/auth/$'
    | '/ops/journeys/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ops/capture'
    | '/ops/consults'
    | '/ops/exceptions'
    | '/ops/packets'
    | '/ops'
    | '/api/auth/$'
    | '/ops/journeys/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/ops'
    | '/ops/capture'
    | '/ops/consults'
    | '/ops/exceptions'
    | '/ops/packets'
    | '/ops/'
    | '/api/auth/$'
    | '/ops/journeys/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/capture': {
      id: '/ops/capture'
      path: '/capture'
      fullPath: '/ops/capture'
      preLoaderRoute: typeof OpsCaptureRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/consults': {
      id: '/ops/consults'
      path: '/consults'
      fullPath: '/ops/consults'
      preLoaderRoute: typeof OpsConsultsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/exceptions': {
      id: '/ops/exceptions'
      path: '/exceptions'
      fullPath: '/ops/exceptions'
      preLoaderRoute: typeof OpsExceptionsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/packets': {
      id: '/ops/packets'
      path: '/packets'
      fullPath: '/ops/packets'
      preLoaderRoute: typeof OpsPacketsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/journeys/$id': {
      id: '/ops/journeys/$id'
      path: '/journeys/$id'
      fullPath: '/ops/journeys/$id'
      preLoaderRoute: typeof OpsJourneysIdRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface OpsRouteChildren {
  OpsCaptureRoute: typeof OpsCaptureRoute
  OpsConsultsRoute: typeof OpsConsultsRoute
  OpsExceptionsRoute: typeof OpsExceptionsRoute
  OpsPacketsRoute: typeof OpsPacketsRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsJourneysIdRoute: typeof OpsJourneysIdRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsCaptureRoute: OpsCaptureRoute,
  OpsConsultsRoute: OpsConsultsRoute,
  OpsExceptionsRoute: OpsExceptionsRoute,
  OpsPacketsRoute: OpsPacketsRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsJourneysIdRoute: OpsJourneysIdRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
